[package]
name = "tokio-fun"
version = "0.1.0"
authors = ["Zachery Hostens <zacheryph@gmail.com>"]

[dependencies]
futures = "0.1"
tokio = "1.8"
# tokio-inotify = "0.4"
inotify = { git = "https://github.com/inotify-rs/inotify" }
