[package]
name = "loan"
version = "0.1.0"
edition = "2018"
authors = ["Zachery Hostens <zacheryph@gmail.com>"]

[lib]
name = "loan"
path = "src/lib.rs"

[[bin]]
name = "loan"
path = "src/main.rs"

[dependencies]
structopt = "0.3.14"
